### ISSUE TITLE
generate github pages site - different repo broken

### ISSUE THREAD

**Issue by DabrowskiAdamPG** [PavanMudigonda/html-reporter-github-pages#10]
Problem:
![image](https://github.com/user-attachments/assets/a1235b98-7266-42d7-8f29-c8417a84a76d)

Solution:
![image](https://github.com/user-attachments/assets/a54ba20b-312c-40ee-8edc-893de4fa0bd8)

PR created:
https://github.com/PavanMudigonda/html-reporter-github-pages/pull/9

**Comment by DabrowskiAdamPG** [comment]
@PavanMudigonda any chance to issue a new release with this change? :)

**Comment by PavanMudigondaTR** [comment]
fixed in v1.4

apologies for delay
