### ISSUE TITLE
Am I able to use this Action on an M1 MacOS machine?

### ISSUE THREAD

**Issue by tking16** [PavanMudigonda/html-reporter-github-pages#11]
I'm attempting to put test results from iOS Appium tests onto Github pages, but I'm getting an error as it tries to deploy, this error wasn't appearing when using ubuntu-latest, but I need to use Mac as that's where the reports are housed

```
/Users/theo/actions-runner/_at-tests/_temp/879262d9-25f2-4dd2-9a48-8165e1a0a210.sh: line 30: /Users/theo/actions-runner/_at-tests/_tool/gh-cli/2.33.0/arm64/bin/gh: cannot execute binary file
Error: Process completed with exit code 126.
```

**Comment by PavanMudigondaTR** [comment]
Hi I will fix it for Mac tomorrow

**Comment by PavanMudigondaTR** [comment]
fixed in v1.4 please try @tking16

**Comment by PavanMudigondaTR** [comment]
@tking16  i just assumed your M1 would have brew installed already. could you please confirm ?

**Comment by tking16** [comment]
Thanks @PavanMudigondaTR, I switched to using Ubuntu for report generation and just having the mac upload the report as an artifact. But I'll try this and let you know
